- name: Test play to get server hostname
  hosts: all
  tasks:
     - name: Get server hostname
       command: hostname
       register: result
        
     - name: Print the command output
       debug:
         msg: The hostname for the server is {{ result.stdout }}
         
